version: '3.8'

x-general-env: &general-env
  MONGO_DB_CONTAINER_PORT: 27017

services:
  stocks1:
    build: ./StocksService
    environment:
      <<: *general-env
      FLASK_APP: StocksService.py
      STOCKS_SERVICE_PORT: 5001
    ports:
      - 5001:8000
    expose:
      # expose this container to other containers
      - 8000
    depends_on:
      - mongodb

  stocks2:
    build: ./StocksService
    environment:
      <<: *general-env
      FLASK_APP: StocksService.py
      STOCKS_SERVICE_PORT: 5002
    ports:
      - 5002:8000
    expose:
      # expose this container to other containers
      - 8000
    depends_on:
      - mongodb

  capital-gains:
    build: ./CapitalGainsService
    environment:
      FLASK_APP: CapitalGainsService.py
      CAPITAL_GAIN_SERVICE_PORT: 5003
    ports:
      - 5003:8080
    depends_on:
      - stocks1
      - stocks2

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  MongoDBService:
    build: ./MongoDBService
    environment:
      <<: *general-env
      FLASK_APP: MongoDBService.py
      MONGO_URI: mongodb://mongodb:27017
    ports:
      - 27017
    expose:
      # expose this container to other containers
      - 27017
    depends_on:
      - mongodb

  nginx:
    build: ./NGINX
    depends_on:
      - stocks1
      - stocks2
    ports:
      - "80:80"

volumes:
  mongo-data:
