x-mongo-uri: &mongo-uri
  MONGO_URI: "mongodb://mongodb:27017"

services:
  stocks1:
    build:
      context: .
      dockerfile: ./StocksService/Dockerfile
    environment:
      <<: *mongo-uri
      COLLECTION_NAME: "stocks1"
    ports:
      - "5001:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb

  stocks2:
    build:
      context: .
      dockerfile: ./StocksService/Dockerfile
    environment:
      <<: *mongo-uri
      COLLECTION_NAME: "stocks2"
    ports:
      - "5002:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb

  capital-gains:
    build:
      context: .
      dockerfile: ./CapitalGainsService/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - stocks1
      - stocks2

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      # expose this container to other containers
      - "27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    build: ./NGINX
    depends_on:
      - stocks1
      - stocks2
    ports:
      - "80:80"

volumes:
  mongo-data:
