x-mongo-container-port-env: &mongo-container-port-env
  MONGO_DB_CONTAINER_PORT: "27017"

services:
  stocks1:
    build:
      context: .
      dockerfile: ./StocksService/Dockerfile
    environment:
      <<: *mongo-container-port-env
      COLLECTION_NAME: "stocks1"
    ports:
      - "5001:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb

  stocks2:
    build:
      context: .
      dockerfile: ./StocksService/Dockerfile
    environment:
      <<: *mongo-container-port-env
      COLLECTION_NAME: "stocks2"
    ports:
      - "5002:8000"
    expose:
      # expose this container to other containers
      - "8000"
    depends_on:
      - mongodb

  capital-gains:
    build:
      context: .
      dockerfile: ./CapitalGainsService/Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - stocks1
      - stocks2

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongodb-service:
    build: ./MongoDBService
    environment:
      <<: *mongo-container-port-env
      # FLASK_APP: MongoDBService
      MONGO_URI: "mongodb://mongodb:27017"
    # ports:
    #   - "27017"
    expose:
      # expose this container to other containers
      - "27017"
    depends_on:
      - mongodb

  nginx:
    build: ./NGINX
    depends_on:
      - stocks1
      - stocks2
    ports:
      - "80:80"

volumes:
  mongo-data:
