apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: stocks-app
spec:
  type: NodePort
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31322