apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  namespace: stocks-app
  labels:
    app: stock-service
spec:
  replicas: 2  # Run two instances of the service
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
      - name: stock-service
        image: stock-service:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000  # Port the app listens on