apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: stocks-app
  labels:
    app: stock-service
spec:
  type: ClusterIP
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 8000  # Exposed port
      targetPort: 8000  # Target port where the app is running