apiVersion: apps/v1
kind: Deployment
metadata:
  name: capital-gains-deployment
  namespace: stocks-app
  labels:
    app: capital-gains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capital-gains
  template:
    metadata:
      labels:
        app: capital-gains
    spec:
      containers:
      - name: capital-gains
        image: capital-gains-image
        ports:
        - containerPort: 8080