apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: stocks-app
  labels:
    app: capital-gains
spec:
  selector:
    app: capital-gains
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8080
  type: ClusterIP
