apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  labels:
    app: capital-gains
spec:
  selector:
    app: capital-gains
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
