apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-db
  namespace: stocks-app
  labels:
    app: stock-service-db
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: stock-service-db
  template:
    metadata:
      labels:
        app: stock-service-db
    spec:
      containers:
      - name: stock-db
        image: mongo:latest  # Using MongoDB image for persistence
        ports:
        - containerPort: 27017  # MongoDB default port
        volumeMounts:
        - name: stock-db-volume
          mountPath: /data/db  # MongoDB stores data in this directory
      volumes:
      - name: stock-db-volume
        persistentVolumeClaim:
          claimName: stock-db-pvc
