apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: stocks-app
  labels:
    app: mongodb
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest  # Using MongoDB image for persistence
        ports:
        - containerPort: 27017  # MongoDB default port
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db  # MongoDB stores data in this directory
      volumes:
      - name: mongodb-volume
        persistentVolumeClaim:
          claimName: mongodb-pvc
