apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-db-pvc
  labels:
    app: stock-service-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi  # Size of storage requested
