apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: stocks-app
  labels:
    app: mongodb
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/mongodb  # Path on the Node's filesystem to store data
