apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: stocks-app
  labels:
    app: mongodb
spec:
  type: ClusterIP  # Default, for internal communication only
  ports:
    - port: 27017
      targetPort: 27017 # MongoDB default port
  selector:
    app: mongodb
