apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: stocks-app
  labels:
    app: mongo
spec:
  type: ClusterIP  # Default, for internal communication only
  ports:
    - port: 27017  # MongoDB default port
      targetPort: 27017
  selector:
    app: mongo
